dataset_dir: "./datasets"

# training options
batch_size: 256 
start_epoch: 0
dataset: "CIFAR10" 
workers: 8

# model options
resnet: "resnet50"
projection_dim: 64 

# linear evaluation epochs
logistic_epochs: 100